stages:
  spg:
    vars:
      - column: spg
      - start: "1993-01"
      - end: "2019-12"
      - container:
          out: /mnt/out
          tmf: /mnt/in/TRACMASS_run.hdf5
          ini: /mnt/in/column_initime.hdf5
          spg: /mnt/in/spg.csv
          par: /params/params.yaml
      - ../../params.yaml
    cmd:
      singularity run --no-home --cleanenv --containall
        --bind $(realpath $(dvc root)/../..)/${data.hdf5}:${container.out}:rw
        --bind $(realpath $(dvc root)/../..)/${data.tracmass_hdf5}:${container.tmf}:ro
        --bind $(realpath $(dvc root)/../..)/${data.initime}:${container.ini}:ro
        --bind $(realpath $(dvc root)/../..)/${data.spg_index}:${container.spg}:ro
        --bind $(realpath $(dvc root)/../..)/params.yaml:${container.par}:ro
      ../../src/dians-${package_version}.sif create_column
        --tracmass-hdf5=${container.tmf}
        --initimecol=${container.ini}
        --column-dst=${container.out}
        --column=${column}
        --index-file=${container.spg}
        --index-start-month=${start}
        --index-end-month=${end}
    deps:
      - ../../params.yaml
      - ../../${data.tracmass_hdf5}
      - ../../${data.initime}
      - ../../${data.spg_index}
      - ../../src/dians-${package_version}.sif
    outs:
      - ../../${data.spg}
